version: '3.1'
services:
  app:
    container_name: app
    image: app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/calendar
      - SPRING_DATASOURCE_USERNAME=calendar_owner
      - SPRING_DATASOURCE_PASSWORD=calendar_owner

  db:
    image: 'postgres:15.2'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=calendar_owner
      - POSTGRES_USER=calendar_owner
      - POSTGRES_DB=calendar

