name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - name: Build And Test
        run: ./gradlew build --no-daemon
      - name: Build Jar
        run: ./gradlew bootJar
      - name: Login in docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta(Set the image name)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: professornik/calendar
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose.yml
          path: docker-compose.yml